server:
   port: 9000
   
spring:
   application:
      name: cloud-config
   cloud:
     config:
        server:
          git:
            # 配置文件分支 ==》现在的默认分支是 main ，以前是master
            default-label: main
            # 配置文件所在仓库
            uri: https://github.com/306529917/config/
            # 配置文件所在根目录
            search-paths: /C89-S3-Ply-cloud
            # 公共仓库不需要配置用户名和密码
            username: 
            password: 
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

           
