server:
   port: 80
   
spring:
   application:
      name: cloud-zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

# 简单路由配置
zuul:
   #    将敏感头设置在 zuul 下，表示对所有的路由的有效
   #    设置要过滤的敏感头， 设置空值可以取消过滤所有的头域字段 ==》 不过滤
   sensitiveHeaders: 
   #    设置要被忽略的头
   # ignoredHeaders:
   routes:
      # 每个路由都有名字， 名字自定
      simple:
         #    请求的地址
         path: /simple/**
         #    跳转的地址，简单路由在配置path的时候是以“http”或“https”开头的。
         url: http://www.163.com
      # 跳转路由   
      myForward:
         path: /us/**
         url: forward:/cloud-user/user/way
      # ribbon路由，直接跳转到服务名下的地址
      users:
         path: /users/**
         serviceId: cloud-user
         # 设置要过滤的敏感头， 设置空值可以取消过滤所有的头域字段 ==》 不过滤
         # sensitiveHeaders: 
      cloud-order:
         path: /orders/**
      # zuul 会默认的将服务名映射称为ribbon 路由
      #cloud-order:
      #   path: /cloud-order/**
      #cloud-user:
      #   path: /cloud-user/**
      
      # 默认路由
     # default:
     #    path: /**
     #    url: https://taobao.com
         
      # zuul 会默认的过滤出 Cookie,Set-Cookie,Authorization 敏感头
      
         
         
         
         
         