server:
   port: 80
   
spring:
   application:
      name: cloud-zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

# 简单路由配置
zuul:
   routes:
      # 每个路由都有名字， 名字自定
      simple:
         #    请求的地址
         path: /simple/**
         #    跳转的地址，简单路由在配置path的时候是以“http”或“https”开头的。
         url: http://www.163.com