server:
   # 8001,8005,8006
   port: 8001
   
spring:
   application:
      name: cloud-user
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
