server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/C89-S3-Ply-mybatis
    username: root
    password: a

mybatis:
  configuration:
	# 开启驼峰命名映射
	mapUnderscoreToCamelCase: true