spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      #&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1/C89-S3-Ply-blog?useSSL=false
      username: root
      password: a
      
logging:
   level:
      com.yc.blog: debug