server:
   # 8002,8007,8008
   port: 8002
   
spring:
   application:
      name: cloud-order
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
# 设定 feign.hystrix.enabled=true，那么Feign将用断路器包装所有的控制层方法
feign:
  hystrix:
    enabled: true
         
# yml 配置片, 使用 三个 -  分隔
---
spring:
   profiles: order8007

server:
   port: 8007
   
---
spring:
   profiles: order8008
server:
   port: 8008