server:
   # 8002,8007,8008
   port: 8002
   
spring:
   application:
      name: cloud-order
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
# yml 配置片, 使用 三个 -  分隔
---
spring:
   profiles: order8007

server:
   port: 8007
   
---
spring:
   profiles: order8008
server:
   port: 8008